name: Banking-Dashboard
options:
  bundleIdPrefix: com.mohamedsalahnassar
  deploymentTarget:
    iOS: 16.0
targets:
  Banking-Dashboard-App:
    type: application
    platform: iOS
    sources:
      - AppSources
    settings:
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      DEVELOPMENT_TEAM: Z46PAR97LP
    dependencies:
      - package: DiamondRevamp
packages:
  DiamondRevamp:
    path: Packages/DiamondRevamp
